import type { Metadata } from "next";
import { ClerkProvider } from '@clerk/nextjs' // UserButton, SignedIn, etc. moved to AuthControls
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthControls from "@/components/AuthControls"; // Import the new component
import { Toast, ToastProvider, ToastViewport } from "@/components/ui/toaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header className="bg-white shadow sticky top-0 z-50">
            <div className="max-w-6xl mx-auto px-4 py-4 flex justify-between items-center">
              <Link href="/" className="text-2xl font-bold text-blue-600 hover:text-blue-700 transition-colors">
                DiagramGen
              </Link>
              <div className="flex items-center gap-6">
                <nav className="flex gap-4">
                  <Link href="/dashboard" className="text-gray-600 hover:text-blue-600 transition-colors">Generator</Link>
                  <Link href="/history" className="text-gray-600 hover:text-blue-600 transition-colors">History</Link>
                </nav>
                <AuthControls />
              </div>
            </div>
          </header>
          <main className="pt-4 pb-8">{children}</main>
          <ToastProvider>
            <Toast />
            <ToastViewport />
          </ToastProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
